"""adcionando password_hash a tabela user

Revision ID: 70a58ad33bcf
Revises: 7b7f65529f9f
Create Date: 2025-03-31 08:54:30.317865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a58ad33bcf'
down_revision = '7b7f65529f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
